version: "2.1"

volumes:
  netdataConfig:
  netdataLib:
  netdataCache:

services:
  netdata:
    build: netdata
    ports:
      - "19999:19999"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.sysfs: 1
    volumes:
      - netdataConfig:/etc/netdata
      - netdataLib:/var/lib/netdata
      - netdataCache:/var/cache/netdata
